language: go

go:
  - '1.10'
  - tip

git:
  depth: 3

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u golang.org/x/lint/golint

install: dep ensure

script:
  - make review-race
  - make build

after_script:
  - bash <(curl -s https://codecov.io/bash)
