language: go
go:
  - '1.11'
  - tip

os:
  - osx
  - linux
  - windows

git:
  depth: 3

## Mark Go version 'tip' as an optional.
matrix:
  exclude:
    - go: tip
      os: windows
  allow_failures:
    - go: 'tip'
  fast_finish: true

## Install dependencies and code review tools.
before_install:
  - export GOBIN="${GOPATH}/bin"
  - ./scripts/tools.sh
  - git fetch --tags

## Install all dependencies, start dependency services.
install:
  - |
    export GO111MODULE=on
    if [ "$TRAVIS_OS_NAME" == windows ]; then
      mingw32-make ci-install
    else
      make ci-install
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start # imitate an display on Linux
    fi

## Check code, perform tests with race-condition-checking.
script: |
  if [ "$TRAVIS_OS_NAME" == windows ]; then
    mingw32-make ci-test
  else
    make ci-test
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    ## Preserve golint executable.
    - $GOBIN
    ## Preserve Go module cache.
    - ${GOPATH}/pkg/mod/cache
